package com.oracle.mapper;

import com.oracle.web.bean.Admin;
import java.util.List;

public interface AdminMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbg.generated Tue May 07 15:52:21 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbg.generated Tue May 07 15:52:21 CST 2019
	 */
	int insert(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbg.generated Tue May 07 15:52:21 CST 2019
	 */
	Admin selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbg.generated Tue May 07 15:52:21 CST 2019
	 */
	List<Admin> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbg.generated Tue May 07 15:52:21 CST 2019
	 */
	int updateByPrimaryKey(Admin record);

	int save(Admin admin);

	Admin queryOne(String userName);

	Admin login(Admin admin);
}