package com.oracle.web.bean;

public class Fenlei {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fenlei.id
     *
     * @mbg.generated Tue May 07 15:52:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fenlei.name
     *
     * @mbg.generated Tue May 07 15:52:21 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fenlei.id
     *
     * @return the value of fenlei.id
     *
     * @mbg.generated Tue May 07 15:52:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fenlei.id
     *
     * @param id the value for fenlei.id
     *
     * @mbg.generated Tue May 07 15:52:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fenlei.name
     *
     * @return the value of fenlei.name
     *
     * @mbg.generated Tue May 07 15:52:21 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fenlei.name
     *
     * @param name the value for fenlei.name
     *
     * @mbg.generated Tue May 07 15:52:21 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

	public Fenlei(Integer id, String name) {
		super();
		this.id = id;
		this.name = name;
	}

	public Fenlei() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public String toString() {
		return "Fenlei [id=" + id + ", name=" + name + "]";
	}
    
    
}